### ISSUE TITLE
libOpenCvNative.so MD5 checksum error

### ISSUE THREAD

**Issue by shiveshk72** [OpenFTC/EasyOpenCV#10] opened 2020-02-09 02:08 UTC
We are trying to use EasyOpenCV on a Moto G5 Plus running Android 7.0 . The libOpenCvNative.so file was copied using the ADB PUSH command to the /sdcard/FIRST folder. On starting the Robot Controller app we are getting the following error - " libOpenCvNative.so is corrupted - libOpenCvNative.so is present in the FIRST on the internal storage. However, the MD5 checksum, does not match what is expected. Any OpenCV-enabled OpModes will likely crash. Delete and re-download the file."

Running the following command using adb shell -
md5sum  libOpenCvNative.so
returns 
07a377983266cb64bd649bb233452970  libOpenCvNative.so

Any hints to what may be causing this ?

**Comment by FROGbots-4634** [comment] 2020-02-09 03:45
Duplicate of https://github.com/OpenFTC/OpenCV-Repackaged/issues/4

**Closed by FROGbots-4634** 2020-02-09 03:45 UTC
